modLoader = "javafml"
loaderVersion = "[1,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL = "https://github.com/The-Aether-Team/The-Aether-Genesis/issues"

[[mods]]
modId = "aether_genesis"
version = "${file.jarVersion}"
displayName = "The Aether: Genesis"
updateJSONURL = "https://github.com/The-Aether-Team/The-Aether-Genesis/raw/1.20.4-develop/update.json"
displayURL = "https://modrinth.com/mod/aether-genesis"
logoFile = "genesis.png"
credits = "The Aether Team, former Aether Team Collaborators for their prior work on The Aether Mod, GitHub contributors for their additional help, Glitchfiend for TerraBlender, the source code of which can be found at https://github.com/Glitchfiend/TerraBlender, and RazorDevs for AeroBlender, the source code of which can be found at https://github.com/RazorDevs/AeroBlender"
authors = "bconlon"
description = '''
    WIP
'''

[[dependencies.aether_genesis]]
    modId="neoforge"
    type = "required"
    versionRange="[20.4.167,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aether_genesis]]
    modId = "aether"
    mandatory = true
    versionRange = "[1.20.4-1.4.0-neoforge,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_genesis]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.4]"
    ordering = "NONE"
    side = "BOTH"
