modLoader = "javafml"
loaderVersion = "[47,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL = "https://github.com/The-Aether-Team/The-Aether-Genesis/issues"

[[mods]]
modId = "aether_genesis"
version = "${file.jarVersion}"
displayName = "The Aether: Genesis"
updateJSONURL = "https://github.com/The-Aether-Team/The-Aether-Genesis/raw/1.20.1-develop/update.json"
displayURL = "https://modrinth.com/mod/aether-genesis"
logoFile = "genesis.png"
credits = "The Aether Team, former Aether Team Collaborators for their prior work on The Aether Mod, GitHub contributors for their additional help, and C4 for Curios API, the source code of which can be found at https://github.com/TheIllusiveC4/Curios"
authors = "bconlon"
description = '''
    WIP
'''

[[dependencies.aether_genesis]]
modId = "forge"
mandatory = true
versionRange = "[47.1.70,]"
ordering = "NONE"
side = "BOTH"
[[dependencies.aether_genesis]]
modId = "aether"
mandatory = true
versionRange = "[1.20.1-1.0.0-beta.2.1-neoforge,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.aether_genesis]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
